package com.example.dynamodbclient.sample.gsi.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Set;

// With GlobalSecondaryIndex
@DynamoDBTable(tableName = "Movie")
public class Movie {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "genre-index")
    private String genre;

    @DynamoDBAttribute
    private Set<String> actors;

    @DynamoDBAttribute
    private String director;

    @DynamoDBAttribute
    private String title;

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public Set<String> getActors() {
        return actors;
    }

    public void setActors(Set<String> actors) {
        this.actors = actors;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    @Override
    public String toString() {
        return "Movie{" +
                "id='" + id + '\'' +
                ", genre='" + genre + '\'' +
                ", actors=" + actors +
                ", director='" + director + '\'' +
                ", title='" + title + '\'' +
                '}';
    }
}
